Repository kcl-lang/kcl, pull requests merged in 2022-05, with the labels that each got.

#12 refactor: refine some code and comments in the sema crate.
  kclvm/sema/src/ty/mod.rs
Labels: documentation

#51 fix: the panic output information of "invalid number" is formatted using PanicInfo.
  kclvm/parser/src/parser/expr.rs
  kclvm/parser/src/tests.rs
Labels: bug

#63 Create cla.yml
  .github/workflows/cla.yml
Labels: ci

#60 refactor: remove internal Issue and PR templates and use .github temp…
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement
