Repository kcl-lang/kcl, pull requests merged in 2022-10, with the labels that each got.

#216 Delim recovery
  kclvm/parser/src/lexer/mod.rs
  kclvm/parser/src/parser/expr.rs
  kclvm/parser/src/parser/tests.rs
  kclvm/parser/src/session/mod.rs
  kclvm/tests/fuzz/Cargo.lock
Labels: parser, error-handling

#227 Create CODE_OF_CONDUCT.md using the default template.
  CODE_OF_CONDUCT.md
Labels: documentation

#228 Refactor(kclvm-tools): move 'printer' from 'kclvm-tools' to 'kclvm-ast'.
  kclvm/Cargo.lock
  kclvm/Cargo.toml
  kclvm/ast_pretty/Cargo.toml
  kclvm/ast_pretty/src/lib.rs
  kclvm/ast_pretty/src/node.rs
  kclvm/ast_pretty/src/test_data/arguments.input
  kclvm/ast_pretty/src/test_data/arguments.output
  kclvm/ast_pretty/src/test_data/codelayout.input
  kclvm/ast_pretty/src/test_data/codelayout.output
  kclvm/ast_pretty/src/test_data/collection_if.input
  kclvm/ast_pretty/src/test_data/collection_if.output
  kclvm/ast_pretty/src/test_data/comment.input
  kclvm/ast_pretty/src/test_data/comment.output
  kclvm/ast_pretty/src/test_data/empty.input
  kclvm/ast_pretty/src/test_data/empty.output
  kclvm/ast_pretty/src/test_data/if_stmt.input
  kclvm/ast_pretty/src/test_data/if_stmt.output
  kclvm/ast_pretty/src/test_data/import.input
  kclvm/ast_pretty/src/test_data/import.output
  kclvm/ast_pretty/src/test_data/index_sign.input
  kclvm/ast_pretty/src/test_data/index_sign.output
  kclvm/ast_pretty/src/test_data/joined_str.input
  kclvm/ast_pretty/src/test_data/joined_str.output
  kclvm/ast_pretty/src/test_data/lambda.input
  kclvm/ast_pretty/src/test_data/lambda.output
  kclvm/ast_pretty/src/test_data/quant.input
  kclvm/ast_pretty/src/test_data/quant.output
  kclvm/ast_pretty/src/test_data/rule.input
  kclvm/ast_pretty/src/test_data/rule.output
  kclvm/ast_pretty/src/test_data/type_alias.input
  kclvm/ast_pretty/src/test_data/type_alias.output
  kclvm/ast_pretty/src/test_data/unary.input
  kclvm/ast_pretty/src/test_data/unary.output
  kclvm/ast_pretty/src/test_data/unification.input
  kclvm/ast_pretty/src/test_data/unification.output
  kclvm/ast_pretty/src/tests.rs
  kclvm/tools/Cargo.toml
  kclvm/tools/src/format/mod.rs
  kclvm/tools/src/lib.rs
  kclvm/tools/src/query/mod.rs
  kclvm/tools/src/query/override.rs
  kclvm/tools/src/query/tests.rs
Labels: feat, refactor

#230 refactor(kcl-vet): move 'schema_name' from struct to mathod generate.
  kclvm/tools/src/vet/expr_builder.rs
  kclvm/tools/src/vet/test_datas/json/complex.k.ast.json
  kclvm/tools/src/vet/test_datas/json/no_schema_name/only_with_bool.ast.json
  kclvm/tools/src/vet/test_datas/json/no_schema_name/only_with_float.ast.json
  kclvm/tools/src/vet/test_datas/json/no_schema_name/only_with_null.ast.json
  kclvm/tools/src/vet/test_datas/json/only_with_bool.ast.json
  kclvm/tools/src/vet/test_datas/json/only_with_bool.json
  kclvm/tools/src/vet/test_datas/json/only_with_float.ast.json
  kclvm/tools/src/vet/test_datas/json/only_with_float.json
  kclvm/tools/src/vet/test_datas/json/only_with_null.ast.json
  kclvm/tools/src/vet/test_datas/json/only_with_null.json
  kclvm/tools/src/vet/test_datas/json/test.ast.json
  kclvm/tools/src/vet/test_datas/yaml/complex.k.ast.yaml
  kclvm/tools/src/vet/test_datas/yaml/json_with_bool.ast.yaml
  kclvm/tools/src/vet/test_datas/yaml/json_with_float.ast.yaml
  kclvm/tools/src/vet/test_datas/yaml/json_with_null.ast.yaml
  kclvm/tools/src/vet/test_datas/yaml/no_schema_name/only_with_bool.ast.yaml
  kclvm/tools/src/vet/test_datas/yaml/no_schema_name/only_with_float.ast.yaml
  kclvm/tools/src/vet/test_datas/yaml/no_schema_name/only_with_null.ast.yaml
  kclvm/tools/src/vet/test_datas/yaml/only_with_bool.ast.yaml
  kclvm/tools/src/vet/test_datas/yaml/only_with_bool.yaml
  kclvm/tools/src/vet/test_datas/yaml/only_with_float.ast.yaml
  kclvm/tools/src/vet/test_datas/yaml/only_with_float.yaml
  kclvm/tools/src/vet/test_datas/yaml/only_with_null.ast.yaml
  kclvm/tools/src/vet/test_datas/yaml/only_with_null.yaml
  kclvm/tools/src/vet/test_datas/yaml/test.ast.yaml
  kclvm/tools/src/vet/tests.rs
Labels: refactor

#234 Feat(kclvm-sema): Update outdated bench tests.
  kclvm/sema/benches/my_benchmark.rs
Labels: enhancement, feat

#232 Fix(kclvm-codegen): fix schema back ref.
  kclvm/compiler/src/codegen/llvm/module.rs
  test/grammar/schema/back_ref/back_ref_1.k
  test/grammar/schema/back_ref/stdout.golden
Labels: bug, fix, codegen

#237 Fix(kclvm-parser): return loading file failed error message from meth…
  kclvm/parser/src/lib.rs
  kclvm/parser/src/parser/tests.rs
Labels: bug, fix

#238 feat: add community link in readme.
  README-zh.md
  README.md
Labels: documentation

#235 refactor: replace json_minimal with serde_json
  kclvm/Cargo.lock
  kclvm/runtime/Cargo.toml
  kclvm/runtime/src/3rdparty/json_minimal/.gitignore
  kclvm/runtime/src/3rdparty/json_minimal/Cargo.toml
  kclvm/runtime/src/3rdparty/json_minimal/LICENSE.md
  kclvm/runtime/src/3rdparty/json_minimal/README.md
  kclvm/runtime/src/3rdparty/json_minimal/src/lib.rs
  kclvm/runtime/src/3rdparty/json_minimal/src/tests.rs
  kclvm/runtime/src/json/json.rs
  kclvm/runtime/src/stdlib/builtin.rs
  kclvm/runtime/src/value/api.rs
  kclvm/runtime/src/value/val_json.rs
  kclvm/runtime/src/value/val_yaml.rs
  kclvm/tests/test_units/runtime/math/test_math.py
Labels: bug, runtime, fix

#233 Fix(kclvm-runner): fix linker bug.
  .github/workflows/kcl.yml
  .github/workflows/macos_test.yaml
  kclvm/runner/src/command.rs
Labels: bug, fix, linker

#242 Fix(kclvm-runner): Before returning the result information, add 'Result::Ok' or 'Result::Err'.
  kclvm/runner/src/exec_data/config.k.fixme
  kclvm/runner/src/exec_data/lambda.k.fixme
  kclvm/runner/src/lib.rs
  kclvm/runner/src/runner.rs
Labels: bug, fix

#239 Refactor(kcl-vet): Add method 'validate()' as the entry point of KCL-Vet.
  kclvm/Cargo.lock
  kclvm/runner/src/lib.rs
  kclvm/tools/Cargo.toml
  kclvm/tools/src/lib.rs
  kclvm/tools/src/vet/expr_builder.rs
  kclvm/tools/src/vet/mod.rs
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/complex.k
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/complex.k.json
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/complex.k.stderr.json
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/complex.k.yaml
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/list.k
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/list.k.json
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/list.k.stderr.json
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/list.k.yaml
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/plain_value.k
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/plain_value.k.json
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/plain_value.k.stderr.json
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/plain_value.k.yaml
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/simple.k
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/simple.k.json
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/simple.k.stderr.json
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/simple.k.yaml
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/test.k
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/test.k.json
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/test.k.stderr.json
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/test.k.yaml
  kclvm/tools/src/vet/test_datas/json/no_schema_name/test.k.ast.json
  kclvm/tools/src/vet/test_datas/json/test.k.ast.json
  kclvm/tools/src/vet/test_datas/json/test.k.json
  kclvm/tools/src/vet/test_datas/validate_cases/complex.k
  kclvm/tools/src/vet/test_datas/validate_cases/complex.k.json
  kclvm/tools/src/vet/test_datas/validate_cases/complex.k.yaml
  kclvm/tools/src/vet/test_datas/validate_cases/list.k
  kclvm/tools/src/vet/test_datas/validate_cases/list.k.json
  kclvm/tools/src/vet/test_datas/validate_cases/list.k.yaml
  kclvm/tools/src/vet/test_datas/validate_cases/plain_value.k
  kclvm/tools/src/vet/test_datas/validate_cases/plain_value.k.json
  kclvm/tools/src/vet/test_datas/validate_cases/plain_value.k.yaml
  kclvm/tools/src/vet/test_datas/validate_cases/simple.k
  kclvm/tools/src/vet/test_datas/validate_cases/simple.k.json
  kclvm/tools/src/vet/test_datas/validate_cases/simple.k.yaml
  kclvm/tools/src/vet/test_datas/validate_cases/test.k
  kclvm/tools/src/vet/test_datas/validate_cases/test.k.json
  kclvm/tools/src/vet/test_datas/validate_cases/test.k.yaml
  kclvm/tools/src/vet/test_datas/yaml/no_schema_name/test.k.ast.yaml
  kclvm/tools/src/vet/test_datas/yaml/test.k.ast.yaml
  kclvm/tools/src/vet/test_datas/yaml/test.k.yaml
  kclvm/tools/src/vet/tests.rs
  kclvm/tools/src/vet/validator.rs
Labels: feat, refactor

#244 Feat(kclvm-version): change new checksum for new version.
  kclvm/version/src/lib.rs
Labels: feat

#246 Refactor(compiler-base): refactor method in DiagnosticHandler.
  compiler_base/error/src/diagnostic/diagnostic_handler.rs
  compiler_base/error/src/diagnostic/tests.rs
Labels: refactor

#245 Feat(compiler-base-session): Add some method for 'Session'.
  compiler_base/error/Cargo.toml
  compiler_base/session/Cargo.toml
  compiler_base/session/src/lib.rs
  compiler_base/session/src/tests.rs
Labels: feat

#248 Feat(compiler_base):add codecov for compiler_base in CI.
  .github/workflows/test_compiler_base.yaml
  .gitignore
  compiler_base/makefile
Labels: enhancement, feat, ci

#254 Feat(compiler_base_session): add a new contructor to `Session`.
  compiler_base/session/src/lib.rs
  compiler_base/session/src/tests.rs
Labels: enhancement, feat

#255 Update compiler base version
  compiler_base/error/Cargo.toml
  compiler_base/session/Cargo.toml
Labels: enhancement, feat

#256 Feat(rustc_error): add trait Debug, PartialEq, Eq for StyledBuffer, StyledString and StyledChar
  compiler_base/3rdparty/rustc_errors/Cargo.toml
  compiler_base/3rdparty/rustc_errors/src/styled_buffer.rs
Labels: feat

#258 Feat(compiler-base-error): Implement trait Debug and PartialEq for Diagnostic.
  compiler_base/error/src/diagnostic/components.rs
  compiler_base/error/src/diagnostic/mod.rs
  compiler_base/error/src/diagnostic/tests.rs
  compiler_base/error/src/emitter.rs
Labels: feat

#259 Feat(compiler-base-error): impl trait Debug for DiagnosticHandler and DiagnosticHandlerInner.
  compiler_base/error/src/diagnostic/diagnostic_handler.rs
  compiler_base/error/src/diagnostic/tests.rs
Labels: feat

#260 Feat(compiler-base-session): Add some methods for Session.
  compiler_base/session/Cargo.toml
  compiler_base/session/src/lib.rs
  compiler_base/session/src/tests.rs
Labels: feat

#262 refactor : use std::box to avoid unnecessary memory alloc
  kclvm/runtime/src/api/kclvm.rs
  kclvm/runtime/src/stdlib/builtin.rs
  kclvm/runtime/src/value/api.rs
  kclvm/runtime/src/value/val.rs
  kclvm/runtime/src/value/val_bin.rs
  kclvm/runtime/src/value/val_clone.rs
  kclvm/runtime/src/value/val_dict.rs
  kclvm/runtime/src/value/val_from.rs
  kclvm/runtime/src/value/val_list.rs
  kclvm/runtime/src/value/val_plan.rs
  kclvm/runtime/src/value/val_schema.rs
  kclvm/runtime/src/value/val_union.rs
Labels: runtime

#264 refactor: refine kclvm codegen and runner for simplifying binary rele…
  kclvm/compiler/Cargo.toml
  kclvm/compiler/src/codegen/llvm/context.rs
  kclvm/compiler/src/codegen/llvm/emit.rs
  kclvm/compiler/src/codegen/llvm/mod.rs
  kclvm/runner/src/assembler.rs
  kclvm/runner/src/command.rs
  kclvm/runner/src/lib.rs
  kclvm/runner/src/runner.rs
  kclvm/runner/src/tests.rs
Labels: refactor, codegen

#261 Refactor: remove cargo clippy errors & warnings from runtime
  kclvm/capi/Cargo.toml
  kclvm/runtime/Cargo.toml
  kclvm/runtime/internal_macros/src/lib.rs
  kclvm/runtime/src/api/utils.rs
  kclvm/runtime/src/context/mod.rs
  kclvm/runtime/src/stdlib/builtin.rs
  kclvm/runtime/src/stdlib/builtin_api.rs
  kclvm/runtime/src/value/api.rs
  kclvm/runtime/src/value/iter.rs
  kclvm/runtime/src/value/val_bin.rs
  kclvm/runtime/src/value/val_bin_aug.rs
  kclvm/runtime/src/value/val_clone.rs
  kclvm/runtime/src/value/val_dict.rs
  kclvm/runtime/src/value/val_fmt.rs
  kclvm/runtime/src/value/val_from.rs
  kclvm/runtime/src/value/val_get_set.rs
  kclvm/runtime/src/value/val_is_in.rs
  kclvm/runtime/src/value/val_json.rs
  kclvm/runtime/src/value/val_len.rs
  kclvm/runtime/src/value/val_list.rs
  kclvm/runtime/src/value/val_overflow.rs
  kclvm/runtime/src/value/val_panic.rs
  kclvm/runtime/src/value/val_schema.rs
  kclvm/runtime/src/value/val_str.rs
  kclvm/runtime/src/value/val_type.rs
  kclvm/runtime/src/value/val_union.rs
  kclvm/tools/src/vet/test_datas/invalid_validate_cases/test.k.stderr.json
Labels: runtime, refactor

#267 Feat(compiler-base-error): add default() to DiagnosticHandler.
  compiler_base/error/Cargo.toml
  compiler_base/error/src/diagnostic/diagnostic_handler.rs
  compiler_base/error/src/diagnostic/diagnostic_message.rs
  compiler_base/error/src/diagnostic/tests.rs
  compiler_base/session/Cargo.toml
Labels: enhancement, feat

#269 Feat(compiler-base-session): Update the new `compiler-base-error/Diag…
  compiler_base/session/Cargo.toml
  compiler_base/session/src/lib.rs
  compiler_base/session/src/tests.rs
Labels: enhancement, error-handling, feat
