Repository kcl-lang/kcl, pull requests merged in 2023-06, with the labels that each got.

#561 fix: fix failed test cases and remove useless variable.
  kclvm/tools/src/LSP/src/test_data/goto_import_def_test/kcl.mod.lock
  kclvm/tools/src/LSP/src/tests.rs
Labels: bug

#568 fix: update go version in Dockerfile and fix bugs
  scripts/docker/kclvm-builder-centos8/Dockerfile
  scripts/docker/kclvm-builder-centos8/Makefile
  scripts/docker/kclvm-builder/Dockerfile
Labels: release

#570 feat: add Github Codespaces development environment support
  .devcontainer/devcontainer.json
  README-zh.md
  README.md
Labels: release

#569 fix: the type of field in ExecProgramArgs has been changed to support serialization from json str
  kclvm/api/src/testdata/exec-program-with-external-pkg.json
  kclvm/api/src/testdata/exec-program-with-external-pkg.response.json
  kclvm/api/src/testdata/hello_import.k
  kclvm/api/src/testdata_external/external/kcl.mod
  kclvm/api/src/testdata_external/external/main.k
  kclvm/api/src/testdata_external/external_1/kcl.mod
  kclvm/api/src/testdata_external/external_1/main.k
  kclvm/ast/src/ast.rs
  kclvm/parser/src/lib.rs
  kclvm/runner/src/runner.rs
  kclvm/runner/src/test_datas/exec_prog_args/default.json
  kclvm/runner/src/test_datas/settings_file/settings.json
Labels: bug

#571 fix: rm the 'Result::unwrap()' in lsp.
  kclvm/driver/src/kpm_metadata.rs
  kclvm/driver/src/tests.rs
Labels: bug

#575 fix: fix ci, adjust the execution method of the test case to serial execution.
  kclvm/cmd/src/tests.rs
Labels: bug

#580 chore: bump kcl version to 0.5.0-alpha.4.
  kclvm/version/src/lib.rs
Labels: release

#582 feat: index sign key name reference in the schema body
  kclvm/compiler/src/codegen/llvm/node.rs
  kclvm/runtime/src/value/api.rs
  kclvm/version/src/lib.rs
  test/grammar/schema/index_signature/key_alias_0/main.k
  test/grammar/schema/index_signature/key_alias_0/stdout.golden
  test/grammar/schema/index_signature/key_alias_1/main.k
  test/grammar/schema/index_signature/key_alias_1/stdout.golden
  test/grammar/schema/index_signature/normal_1/stdout.golden
  test/grammar/schema/index_signature/normal_5/main.k
  test/grammar/schema/index_signature/normal_5/stdout.golden
Labels: semantic, codegen

#583 fix: unsound schema runtime check.
  kclvm/compiler/src/codegen/llvm/node.rs
  kclvm/runtime/src/_kclvm.bc
  kclvm/runtime/src/_kclvm.h
  kclvm/runtime/src/_kclvm.ll
  kclvm/runtime/src/_kclvm_api_spec.rs
  kclvm/runtime/src/stdlib/builtin.rs
  kclvm/runtime/src/value/api.rs
  kclvm/runtime/src/value/val_json.rs
  kclvm/runtime/src/value/val_plan.rs
  test/grammar/schema/optional_attr/fail_4/main.k
  test/grammar/schema/optional_attr/fail_4/stderr.golden.py
  test/grammar/schema/optional_attr/fail_5/main.k
  test/grammar/schema/optional_attr/fail_5/stderr.golden.py
  test/grammar/schema/optional_attr/fail_6/main.k
  test/grammar/schema/optional_attr/fail_6/stderr.golden.py
  test/grammar/schema/relaxed/fail_0/main.k
  test/grammar/schema/relaxed/fail_0/stderr.golden.py
  test/grammar/schema/relaxed/fail_1/main.k
  test/grammar/schema/relaxed/fail_1/stderr.golden.py
Labels: runtime

#584 refactor: runner code for better error messages.
  kclvm/runner/benches/bench_runner.rs
  kclvm/runner/src/assembler.rs
  kclvm/runner/src/command.rs
  kclvm/runner/src/lib.rs
  kclvm/runner/src/linker.rs
  kclvm/runner/src/runner.rs
  kclvm/runner/src/tests.rs
Labels: refactor, runner

#586 refactor: value union with options.
  kclvm/runtime/src/value/api.rs
  kclvm/runtime/src/value/val_bin.rs
  kclvm/runtime/src/value/val_bin_aug.rs
  kclvm/runtime/src/value/val_dict.rs
  kclvm/runtime/src/value/val_union.rs
Labels: runtime, refactor

#589 refactor: enhance cli error messages for run and vet commands.
  kclvm/config/src/settings.rs
  kclvm/runtime/src/value/val_plan.rs
  kclvm/tools/src/vet/expr_builder.rs
  kclvm/tools/src/vet/tests.rs
  kclvm/tools/src/vet/validator.rs
Labels: tool, refactor
