Repository kcl-lang/kcl, pull requests merged in 2023-07, with the labels that each got.

#590 feat: enhance override with compact style.
  kclvm/query/src/override.rs
  kclvm/query/src/tests.rs
Labels: tool, api

#591 docs: move github codespace links to the contributing section.
  README-zh.md
  README.md
Labels: docs

#592 chore: bump cla kcl bot
  .github/workflows/cla.yml
  .github/workflows/macos_test.yaml
Labels: ci

#593 fix: fix empty identifier expr position
  kclvm/parser/src/parser/expr.rs
  kclvm/tools/src/LSP/src/completion.rs
  kclvm/tools/src/LSP/src/test_data/completion_test/dot/completion.k
  kclvm/tools/src/LSP/src/tests.rs
Labels: bug, parser, lsp

#599 feat: update github workflow
  .github/workflows/macos_test.yaml
  .github/workflows/ubuntu_test.yaml
  .github/workflows/windows_test.yaml
Labels: ci

#600 fix: runtime literal union type check.
  kclvm/runtime/src/value/val_type.rs
  test/grammar/types/literal/lit_07_uf8_str_union/main.k
  test/grammar/types/literal/lit_07_uf8_str_union/stdout.golden
Labels: runtime

#601 chore: bump docker namespace to kcllang.
  .devcontainer/devcontainer.json
  .github/workflows/release.yaml
  .github/workflows/ubuntu_test.yaml
  Makefile
  docs/dev_guide/2.quick_start.md
  internal/scripts/cli/kcl-test
  scripts/docker/kcl-builder-centos7/Dockerfile
  scripts/docker/kcl-builder-centos7/Makefile
  scripts/docker/kcl-builder-centos8/Dockerfile
  scripts/docker/kcl-builder-centos8/Makefile
  scripts/docker/kcl-builder/Dockerfile
  scripts/docker/kcl-builder/Makefile
  scripts/docker/kcl/Dockerfile
  scripts/docker/kclvm-builder-centos7/timestamp.go
  scripts/docker/kclvm/.keep
Labels: release

#604 chore: bump kcl 0.5.0 artifact
  .github/workflows/macos_test.yaml
  .github/workflows/ubuntu_test.yaml
  .github/workflows/windows_test.yaml
  VERSION
  kclvm/version/src/lib.rs
Labels: release

#605 fix: canonicalize the symlink path in method 'canonicalize_input_files'.
  kclvm/cmd/src/test_data/sym_link/origin/a.k
  kclvm/cmd/src/test_data/sym_link/origin/sub/a.k
  kclvm/cmd/src/tests.rs
  kclvm/driver/src/lib.rs
Labels: bug

#609 chore: add the maintainer file
  MAINTAINERS
Labels: chore

#612 bugfix: if_stmt orelse postion
  kclvm/parser/src/parser/stmt.rs
  kclvm/parser/testdata/if-02.k
  kclvm/parser/testdata/if-02.k.json
  kclvm/tools/src/LSP/src/tests.rs
Labels: parser

#618 refactor: enhance kcl and its tool cli error message and add more tests.
  kclvm/api/src/service/capi.rs
  kclvm/api/src/service/service_impl.rs
  kclvm/cmd/src/lib.rs
  kclvm/cmd/src/lint.rs
  kclvm/cmd/src/test_data/lint/test.k
  kclvm/cmd/src/tests.rs
  kclvm/driver/src/lib.rs
  kclvm/runner/src/lib.rs
  kclvm/runtime/src/_kcl_run.rs
  kclvm/src/lib.rs
  kclvm/tools/src/format/mod.rs
  kclvm/tools/src/format/tests.rs
Labels: error-handling, refactor

#617 ci: add backport action
  .github/workflows/backport.yaml
Labels: ci

#619 fix: fix performance regression on resolver::parse_doc_string
  kclvm/Cargo.lock
  kclvm/sema/Cargo.toml
  kclvm/sema/src/resolver/doc.rs
Labels: refactor, resolver

#614 feat: lsp completion of pkg, var and schema attr
  kclvm/sema/src/lint/lints_def.rs
  kclvm/sema/src/resolver/import.rs
  kclvm/sema/src/resolver/scope.rs
  kclvm/sema/src/resolver/tests.rs
  kclvm/tools/src/LSP/src/completion.rs
  kclvm/tools/src/LSP/src/document_symbol.rs
  kclvm/tools/src/LSP/src/goto_def.rs
  kclvm/tools/src/LSP/src/test_data/completion_test/dot/completion.k
  kclvm/tools/src/LSP/src/tests.rs
  kclvm/tools/src/LSP/src/util.rs
Labels: lsp

#623 chore: bump serde_yaml to latest to solve security issues and error test cases
  VERSION
  kclvm/Cargo.lock
  kclvm/api/Cargo.toml
  kclvm/config/Cargo.toml
  kclvm/runner/src/custom_manifests_data/list.stdout.golden
  kclvm/runtime/Cargo.toml
  kclvm/runtime/src/manifests/tests.rs
  kclvm/runtime/src/manifests/yaml.rs
  kclvm/runtime/src/value/val_yaml.rs
  kclvm/tools/Cargo.toml
  test/grammar/builtins/default/bin/stdout.golden
  test/grammar/builtins/default/oct/stdout.golden
  test/grammar/schema/union/binary_union/binary_union_5/stdout.golden
Labels: release, dependencies, security

#622 feat: support for taking mod relative paths as input.
  kclvm/Cargo.lock
  kclvm/cmd/src/test_data/multimod/kcl1/kcl.mod
  kclvm/cmd/src/test_data/multimod/kcl1/main.k
  kclvm/cmd/src/test_data/multimod/kcl2/kcl.mod
  kclvm/cmd/src/test_data/multimod/kcl2/main.k
  kclvm/cmd/src/test_data/multimod/kcl3/kcl.mod
  kclvm/cmd/src/test_data/multimod/kcl3/kcl4/kcl.mod
  kclvm/cmd/src/test_data/multimod/kcl3/kcl4/main.k
  kclvm/cmd/src/test_data/multimod/kcl3/main.k
  kclvm/cmd/src/tests.rs
  kclvm/config/Cargo.toml
  kclvm/config/src/lib.rs
  kclvm/config/src/modfile.rs
  kclvm/config/src/path.rs
  kclvm/config/src/testdata/multimods/kcl1/kcl.mod
  kclvm/config/src/testdata/multimods/kcl1/main.k
  kclvm/config/src/testdata/multimods/kcl2/kcl.mod
  kclvm/config/src/testdata/multimods/kcl2/main.k
  kclvm/driver/src/lib.rs
  kclvm/parser/Cargo.toml
  kclvm/parser/src/lib.rs
  kclvm/tools/src/LSP/src/test_data/goto_import_def_test/kcl.mod
Labels: enhancement

#626 chore: add more maintainers
  MAINTAINERS
Labels: chore

#630 bugfix: endless loop in if stmt error recovery
  kclvm/parser/src/parser/stmt.rs
  kclvm/parser/src/tests/error_recovery.rs
  kclvm/parser/src/tests/snapshots/kclvm_parser__tests__error_recovery__if_stmt_recovery_7.snap
Labels: bug, parser
